# Generated by Django 5.0.4 on 2024-08-10 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
