# Generated by Django 5.0.4 on 2024-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0002_alter_command_date_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
