# Generated by Django 5.0.4 on 2024-08-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0003_command_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='adrress_client',
            new_name='address_client',
        ),
    ]
