# Generated by Django 5.0.4 on 2024-08-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0004_rename_adrress_client_command_address_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='Vegetable',
            new_name='vegetable',
        ),
    ]
