# Generated by Django 5.0.4 on 2024-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0005_rename_vegetable_command_vegetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='commune_client',
            field=models.CharField(default='Gombe', max_length=200),
        ),
    ]
