# Generated by Django 5.1 on 2024-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0006_command_commune_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('last_name_user', models.CharField(max_length=200)),
                ('adress_user', models.CharField(max_length=200)),
                ('commune_user', models.CharField(max_length=200)),
                ('commands', models.CharField(max_length=500)),
            ],
        ),
    ]
