# Generated by Django 5.1 on 2024-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('email_user', models.CharField(max_length=200)),
                ('suggestions', models.CharField(max_length=500)),
            ],
        ),
    ]
