# Generated by Django 5.1 on 2024-08-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0008_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commands',
        ),
    ]
