# Generated by Django 5.1 on 2024-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0009_remove_user_commands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
