# Generated by Django 5.1 on 2024-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0011_command_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
