# Generated by Django 5.1 on 2024-08-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_shop', '0012_vegetable_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='commune_client',
            field=models.CharField(max_length=200),
        ),
    ]
